### ISSUE TITLE
Useful to non-Zalandos?

### ISSUE THREAD

**Issue by Lauriapple1** [zalando/bdist_docker#1]
Seems like it--maybe with more documentation we can promote?

**Comment by jmcs** [comment]
I need to get some one to review it to make sure it is generic enough. Right now I think this is only used by lizzy.

**Comment by hjacobs** [comment]
I'm personally also not using it, because I don't want to use language-specific Docker build integrations (Maven also has a plugin).

**Comment by Lauriapple1** [comment]
@jmcs would you like some help on this? @hjacobs not clear on if your comment suggests that we abandon this project or not. Does the Maven plugin make this project duplicative or superfluous?

**Comment by hjacobs** [comment]
@LauriZalando @jmcs my comment was basically saying that I (personally) don't use the project (but I would be the target audience as a Python+Docker user) --- i.e. I have no strong feelings here ;-)

**Comment by lasomethingsomething** [comment]
Thanks, @hjacobs. If you're the target audience but not using it, that tells me that it might not be a project we want to grow. Maybe I'm wrong, but it seems that a lot of developers would also want a language-agnostic Docker build integration in order to avoid an unnecessary constraint?
